### ISSUE TITLE
Can't open Image files

### ISSUE THREAD

**Issue by ITHMedia** [JanArnoCoetzer/QuickSearchBuild#2]
When attempting to open a image file, after selecting which application to use in a pop-up, nothing happens, Issue on JPG Jpeg and PNG filetypes.

**Comment by JanArnoCoetzer** [comment]
User experienced an issue where JPG and PNG files are not opening in File Explorer. The problem is not with the file explorer app itself, but rather with the Windows environment, which is trying to open the image files with an incorrect/unstable application for images. bug tracked down to the photos app not opening the image.
